Gemfile.lock
README.md
libraries/drivers_db_base.rb
libraries/drivers_db_factory.rb
libraries/helpers.rb
metadata.rb
package.json
recipes/configure.rb
recipes/deploy.rb
recipes/setup.rb
recipes/shutdown.rb
recipes/undeploy.rb
spec/fixtures/node.rb
spec/unit/examples/db_parameters_and_connection.rb
spec/unit/libraries/drivers_db_factory_spec.rb
spec/unit/recipes/configure_spec.rb
spec/unit/recipes/setup_spec.rb

The database adapter and parameters can be defined in the
node (custom json) if an RDS resource is not defined.
This is expected behaviour for Opsworks users.
BREAKING CHANGE: Sqlite3 is no longer set as the default database
adapter.
In order to use sqlite as the database adapter it must be defined
in the node.

feat: eliminate RDS requirement

---

README.md
libraries/drivers_appserver_null.rb
libraries/drivers_webserver_null.rb
spec/unit/libraries/drivers_appserver_factory_spec.rb
spec/unit/libraries/drivers_appserver_null_spec.rb
spec/unit/libraries/drivers_webserver_factory_spec.rb
spec/unit/libraries/drivers_webserver_null_spec.rb

Adding null object for appserver and webserver adapters. Customize instances on a worker layer vs an appserver layer.

Layer switch

---

attributes/default.rb
libraries/drivers_worker_sidekiq.rb
spec/unit/recipes/configure_spec.rb

Enabling workers on amazon linux fails due to monit paths. Add configurable monit dirs and default based on platform.

feat: Added monit compatibility with amazon linux

---

libraries/drivers_worker_sidekiq.rb

related to this issue
https://github.com/ajgon/opsworks_ruby/issues/29

fix: Reload monit after restarting services

---

libraries/helpers.rb

didn't know how to write a test for this, but it's super simple.
related to issue https://github.com/ajgon/opsworks_ruby/issues/31

fix: specify bundle path on bundle install

---

libraries/helpers.rb
recipes/configure.rb
recipes/deploy.rb
spec/unit/recipes/configure_spec.rb

Gems are currently being installed in the release path. When a new release is created, all the gems must be installed again. By caching the gems in the shared folder we can speed up the deployments considerably.

Caching bundle installs to speed up deployments

---

libraries/drivers_appserver_null.rb

This ensures the dotenv/application.yml options are still considered.  Useful for process servers that don't need an app server.

Allow deploy_before_restart on null appserver

---

libraries/drivers_db_mysql.rb

Aurora is backwards compatible with MySQL

Add aurora as allowed engine for mysql2 adapter

---

Gemfile.lock

Per https://github.com/lostisland/faraday_middleware/issues/152, bundler
started reporting that 0.11.0 could not be installed due to a checksum
mismatch. To remedy the issue, the faraday middleware team has released
a patch version to allow users to bundle install from scratch again.
I am unsure as to whether or not this project prefers 1.13.17 for
bundler, or always the latest release but I am including the change here
as it is relevant when hitting this issue.
No breaking changes should be introduced here.

fix: Bump faraday middleware version

---

attributes/default.rb
recipes/deploy.rb

Allow increased timeout on deploy.  Specific use case is for migrations that take a long time.
Please, squash and merge.

feat(framework): Allow increased timeout during deploy

---

templates/default/appserver.nginx.conf.erb

I think that it is better to hide version info.

feat(webserver): server_tokens off on Nginx

---

.fasterer.yml
docs/source/attributes.rst
libraries/helpers.rb
spec/unit/recipes/deploy_spec.rb

Some Opsworks users deploy their apps on custom AMIs with strict
partitioning schemes and disk space limitations. For these users
the default deploy directory /srv/www is not always a good choice.
This patch allows users to override the deploy directory at the
application level by specifying the attribute
`node['deploy'][shortname]['global']['deploy_dir']`
The default value for the app-specific deploy directory continues to be
/srv/www/shortname.
Fixes #95

feat(global): support per-application deploy directory

---

.kitchen.yml
docs/source/attributes.rst
libraries/drivers_db_base.rb
libraries/drivers_db_null.rb
libraries/drivers_db_sqlite.rb
libraries/drivers_framework_base.rb
libraries/drivers_framework_rails.rb
recipes/deploy.rb
spec/unit/recipes/configure_spec.rb
test/integration/data_bags/maximum_override/aws_opsworks_app/other_project.json
test/integration/maximum_override/serverspec/maximum_override_spec.rb

Support null database driver

---

.kitchen.yml
attributes/default.rb
docs/source/attributes.rst
libraries/drivers_db_base.rb
libraries/drivers_db_null.rb
libraries/drivers_db_sqlite.rb
libraries/drivers_framework_base.rb
libraries/drivers_framework_rails.rb
libraries/drivers_webserver_apache2.rb
libraries/drivers_webserver_base.rb
libraries/drivers_webserver_nginx.rb
recipes/deploy.rb
spec/unit/recipes/configure_spec.rb
templates/default/appserver.apache2.conf.erb
templates/default/appserver.nginx.conf.erb
test/integration/data_bags/maximum_override/aws_opsworks_app/other_project.json
test/integration/maximum_override/serverspec/maximum_override_spec.rb

Allow the user to deploy multiple applications on a single server,
each listening on a distinct port:
`app['webserver']['port']` and `app['webserver']['ssl_port']` (default
80 and 443, respectively), as well as the corresponding `global` values,
will allow the user to override the port that the application listens to
in Apache2 or nginx.
Allow user to override which template is used to generate Apache2 or
nginx per-app webserver configurations (aka "site configs"):
`app['webserver']['site_config_template']` and
`app['webserver']['site_config_template_cookbook']` (defaults are
`appserver.#{webserver}.conf.erb` and `opswork_ruby`, respectively), as
well as the corresponding `global` values, will allow the user to
specify which template (from which cookbook) should be used to render
the …

Support arbitrary customization of webserver site configuration

---

.kitchen.yml
attributes/default.rb
docs/source/attributes.rst
libraries/drivers_webserver_apache2.rb
spec/unit/recipes/configure_spec.rb
test/integration/data_bags/maximum_override/aws_opsworks_app/yet_another_project.json
test/integration/maximum_override/serverspec/maximum_override_spec.rb

In order to ensure that default sites provided by the OS
package manager did not conflict with application site
configs, the apache2 provider was over-enthusiastically
deleting *all* enabled sites every time it configured and
enabled any site. Also this had the effect of getting rid
of any enabled default site config, it also got rid of
any other enabled application site config, making it
impossible to run multiple apps under the same Apache2
web server. Some of us actually do that! So this fixes it.
Fixes #111

fix(webserver): Only remove default enabled sites

---

libraries/drivers_dsl_logrotate.rb

cleanup from [commit](https://github.com/ajgon/opsworks_ruby/commit/eabf207662b50edbe0e825c2175d44a835309941)
this method was accidentally left in there when i was testing. its safe to remove and not being used.

chore: remove unused method from logrotate module

---

.travis.yml

Hi,
The default **ruby** version on  *Amazon Linux* is `2.0.0`.
It could be useful to test this against this ruby version.
Regards,
PS : The last version is `2.4.2`, I have changer from `2.4.0`

Use several ruby version

---

.travis.yml

I notice that in my PR #136, the system gems was added to CI cache.
So caching was inefficient

ci(cache): avoid caching system gems

---

libraries/drivers_appserver_puma.rb
libraries/drivers_appserver_thin.rb
libraries/drivers_appserver_unicorn.rb
spec/unit/recipes/configure_spec.rb

ex)
$ /srv/www/rails/shared/scripts/puma.service start
Set Puma process UID to 5000
Starting Puma rails
cd /srv/www/rails/current && /usr/local/bin/bundle exec puma -C #{ROOT_PATH}/shared/config/puma.rb
/srv/www/rails/shared/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/cli.rb:47:in `initialize': missing argument: -C (OptionParser::MissingArgument)
from /srv/www/rails/shared/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/bin/puma:8:in `new'
from /srv/www/rails/shared/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/bin/puma:8:in `<top (required)>'
from /srv/www/rails/shared/vendor/bundle/ruby/2.4.0/bin/puma:23:in `load'
from /srv/www/rails/shared/vendor/bundle/ruby/2.4.0/bin/puma:23:in `<main>'

fix: failed to start appserver.

---

libraries/drivers_db_postgresql.rb
spec/unit/recipes/setup_spec.rb

we need to have packages in sync with RDS to use tools like `pg_dump` (currently getting an error message `pg_dump: aborting because of server version mismatch`)

bumps postgresql package to 9.6 (current RDS default)

---

attributes/default.rb
docs/source/attributes.rst
libraries/drivers_appserver_base.rb
libraries/drivers_appserver_puma.rb
spec/fixtures/node.rb
spec/unit/libraries/drivers_appserver_puma_spec.rb
spec/unit/recipes/deploy_spec.rb
spec/unit/recipes/undeploy_spec.rb
templates/default/appserver.service.erb
templates/default/puma.rb.erb
test/integration/all_options/serverspec/all_options_spec.rb
test/integration/default/serverspec/default_spec.rb
test/integration/http_unicorn_apache_hanami_resque/serverspec/http_unicorn_apache_hanami_resque_spec.rb
test/integration/maximum_override/serverspec/maximum_override_spec.rb
test/integration/s3_thin_nginx_padrino_delayed_job/serverspec/s3_thin_nginx_padrino_delayed_job_spec.rb

The standard appserver service script current performs a stop-start cycle at the end of a deploy to load new code.  This is a bit problematic in production environments.  The appserver 'stop' closes the socket that nginx communicates with, which causes it to immediately return 502 responses.  This will continue until the appserver boot is completed and a new socket is established.  The net result is that requests to the application during the stop-start cycle will be lost.
Puma provides a facility to avoid this problem by issuing a 'restart' instead.  This keeps the socket open and reloads the code.  This causes requests that are received during the restart to hang until the app server finishes booting. 
Puma also provides several hooks for various events that occur during the worker / …

Puma restart / hook support

---

templates/default/appserver.apache2.passenger.conf.erb

fix: add Apache 2.4's "Require all granted" to apache2+passenger config

---

docs/source/attributes.rst
libraries/drivers_appserver_puma.rb
libraries/drivers_appserver_thin.rb
libraries/drivers_appserver_unicorn.rb
templates/default/puma.rb.erb
templates/default/thin.yml.erb
templates/default/unicorn.conf.erb

this will allow people to separate out the appserver into its own container or server from the web server. Useful when there are compliance rules to separate these layers. Or if there is no benefit for a web server like when serving an api and routing on some other layer like the lb.
[issue](https://github.com/ajgon/opsworks_ruby/issues/162)

Config bind

---

libraries/drivers_db_postgresql.rb

There is a typo for Aurora PostgreSQL adapter. This PR fix it 😉

Fix typo for aurora postgresql

---

recipes/configure.rb

This directory is symlinked by default here:
https://github.com/ajgon/opsworks_ruby/blob/6e2328941996d98316657d7a52c98de6982068a5/attributes/default.rb#L21
But the directory is never created and we're left with a broken symlink.

Ensure shared/system dir is created

---

recipes/setup.rb

Fix following error.
```
================================================================================
Error executing action `run` on resource 'execute[apt-get -q update]'
================================================================================
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q update ----
STDOUT: Hit:1 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Hit:5 …
```

fix: register gpg public key for nginx on ubuntu18.04LTS

---

templates/default/appserver.service.erb

We encountered an issue with the combined configuration of using a `unicorn` appserver and `clean-restart` as the after-deploy action.
To reproduce, we ran `bundle update` on a gem that changed the patch level of a gem without changing the contents of the `Gemfile`.  By using the `Gemfile.lock` instead to determine whether installed library changes have occurred, we managed the mitigate the issue.

Compare lockfiles instead of main Gemfile

---

libraries/drivers_worker_sidekiq.rb
spec/unit/recipes/configure_spec.rb
spec/unit/recipes/shutdown_spec.rb
templates/default/sidekiq.monitrc.erb

Without this change, I get the following error when running setup:
```
[2019-05-07T22:49:06+00:00] ERROR: execute[/bin/su - deploy -c "ps -ax | grep 'bundle exec sidekiq' | grep sidekiq_1.yml | grep -v grep | awk '{print $1}' | xargs kill -TSTP"] (opsworks_ruby::deploy line 52) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '123'
---- Begin output of /bin/su - deploy -c "ps -ax | grep 'bundle exec sidekiq' | grep sidekiq_1.yml | grep -v grep | awk '{print $1}' | xargs kill -TSTP" ----
STDOUT:
STDERR: kill: invalid argument c
Usage:
kill [options] <pid> [...]
Options:
<pid> [...]            send signal to every <pid> listed
-<signal>, -s, --signal <signal>
specify the <signal> to be sent
-l, --list=[<signal>]  list all signal names, or …
```

Fix quieting and stopping sidekiq

---

libraries/drivers_webserver_nginx.rb

There is a default nginx server configuration in `/etc/nginx/conf.d/default.conf`.  It is acting as `default_server` instead of `/etc/nginx/sites-enabled/my-app.conf`.  This means the load balancers cannot connect to the app.
It's acting as the default server because it gets included first.
```
http {
...
include /etc/nginx/conf.d/*.conf;
include /etc/nginx/sites-enabled/*;
}
```
This PR simply removes that default server file.
Not sure why this suddenly started happening.  I noticed this after upgrading an older stack from opsworks_ruby 1.4 to 1.15.

fix(webserver): remove default nginx config from conf.d

---

docs/source/attributes.rst
libraries/drivers_worker_base.rb

I had a need to modify the monitrc in a special case.
This PR adds `app['worker']['monit_template_cookbook']` with a default of `opsworks_ruby`.

Allow selection of cookbook for worker monitrc template.

---

docs/attributes.md

Fixes a mistake in `worker` section. Instead of `app['webserver']['adapter']` it should be `app['worker']['adapter']`

Update attributes documentation

---

.kitchen.yml
attributes/default.rb
docs/attributes.md
libraries/drivers_appserver_base.rb
libraries/drivers_worker_base.rb
libraries/drivers_worker_shoryuken.rb
libraries/drivers_worker_sidekiq.rb
libraries/helpers.rb
test/integration/all_options/serverspec/all_options_spec.rb

When the monit start script exceeds 4kb monit (any version under 5.27.0) isn't able to monitor the process. 
reference to the [issue](https://bitbucket.org/tildeslash/monit/issues/851) on monit which has to do with the ps command buffer.
reference to the [changelog](https://bitbucket.org/tildeslash/monit/src/release-5-27-0/CHANGES) that includes this fix.
My servers use an older version of monit, and amazon linux has even older versions. This Pr allows workers to use dot env rather than storing all of them in the monit file, just like the app server already does.

feat(worker): worker option to use dot env
